version: '3.8'

services:
  db:
    image: mysql/mysql-server:8.0.30
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: python:3.9
    container_name: app
    volumes:
      - .:/app
      - ./your-local-dir:/app/your-container-dir
    working_dir: /app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: Maithani@2002
      DB_NAME: company_data
      RAPIDAPI_KEY: 40668e06c2msh19671a3f489e36ep1fa55djsn9d068d9f015a
    command: >
      /bin/bash -c "pip install -r requirements.txt && python main.py"

volumes:
  mysql-data:
